# Generated by Django 6.0.7 on 2026-08-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=200)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('p_img_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
