# Generated by Django 6.0.7 on 2026-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='p_img',
            field=models.ImageField(blank=True, max_length=500, upload_to='products/'),
        ),
    ]
