# Generated by Django 6.0.7 on 2026-08-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuv', '0002_remove_product_p_img_url_product_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
